# Generated by Django 3.2.12 on 2022-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('calories', models.IntegerField(blank=True, default=0, verbose_name='Calories')),
                ('fat', models.FloatField(blank=True, default=0, verbose_name='Fat (g)')),
                ('carbs', models.IntegerField(blank=True, default=0, verbose_name='Carbs (g)')),
                ('protein', models.FloatField(blank=True, default=0, verbose_name='Protein (g)')),
                ('iron', models.CharField(blank=True, max_length=4, verbose_name='Iron (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年齢')),
                ('stateInPark', models.IntegerField(default=0, verbose_name='状態1')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='部屋名')),
                ('board', models.CharField(max_length=9, verbose_name='盤面')),
                ('record', models.CharField(max_length=9, verbose_name='棋譜')),
            ],
        ),
    ]
