# Generated by Django 3.2.12 on 2022-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('calories', models.IntegerField(blank=True, default=0, verbose_name='Calories')),
                ('fat', models.FloatField(blank=True, default=0, verbose_name='Fat (g)')),
                ('carbs', models.IntegerField(blank=True, default=0, verbose_name='Carbs (g)')),
                ('protein', models.FloatField(blank=True, default=0, verbose_name='Protein (g)')),
                ('iron', models.CharField(blank=True, max_length=4, verbose_name='Iron (%)')),
            ],
        ),
    ]
