# Generated by Django 3.2.12 on 2022-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0002_dessert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeRoom3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25, verbose_name='部屋名')),
                ('board', models.CharField(max_length=9, verbose_name='盤面')),
                ('record', models.CharField(max_length=9, verbose_name='棋譜')),
            ],
        ),
    ]
