# Generated by Django 3.2.12 on 2022-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0004_rename_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stateInPark',
            field=models.IntegerField(default=0, verbose_name='状態1'),
        ),
    ]
