# Generated by Django 3.2.12 on 2022-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='match_state',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='対局のマッチング状態'),
        ),
    ]
